language: python
python:
  - 3.5
  - 3.6

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install tox coveralls coverage
script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
  - coveralls
